### ISSUE TITLE
MKR1010 BLE - Timeout issue 

### ISSUE THREAD

**Issue by sprasadkrish** [arduino-libraries/ArduinoBLE#109]
Hardware :MKR 1010WIFI ( for BLE) 
Arduino lib :  version 1.1.3 

I am using one central and two peripherals for data receiving.

 CentralBLE always receives data, based on a request to peripheralsBLE.
Example: CentralBLE request peripheralBLE-1, to send data, peripheralBEL-1 send data to CentralBLE similarly 
              peripheralBLE-2 also.
              CentralBLE request peripheralBLE-2, to send data, peripheralBEL-2 send data to CentralBLE
              
Issue:
Central receive data up to 2 minutes , after two minutes , central disconnect peripheral and stop receiving data . There is any possible to increase the timeout of Central BLE , or possible to set NO TIMEOUT in CentralBLE(continues data transfer).

sketch :
[CENTRAL_V11.0.txt](https://github.com/arduino-libraries/ArduinoBLE/files/5112067/CENTRAL_V11.0.txt)
[PERIPHERAL_1_V11.0.txt](https://github.com/arduino-libraries/ArduinoBLE/files/5112069/PERIPHERAL_1_V11.0.txt)
[PERIPHERAL_2_V11_0.txt](https://github.com/arduino-libraries/ArduinoBLE/files/5112070/PERIPHERAL_2_V11_0.txt)

**Comment by Polldo** [comment]
Hi @sprasadkrish ,
There isn't any timeout limiting the maximum connection time. So, the problem should reside in your sketches.
I can give you the following advice.
- Maintain two concurrent connections instead of disconnecting from each a peripheral after a read.
- Catch and handle the cases in which arduinoBLE functions execution fails (returning 0) 
- Substitute the delay statement with a busy cycle that calls the BLE polling function (see example below)

handle scan enable failures
```C++
int ret = 0;
while (!ret) {
  ret = BLE.scanForUuid("19b10000-e8f2-537e-4f6c-d104768a1214");
}
```  

substitute delays
```C++
unsigned long timeRef = millis();
void loop() 
{
  // substitute the delay with a busy cycle that calls the BLE polling function
  // delay(3000);
  timeRef = millis();
  while (millis() < timeRef + 3000) {
    BLE.poll();
  }
...
}
  
```
Regarding the first point I mentioned above, take a look at this https://github.com/arduino-libraries/ArduinoBLE/pull/105 . This commit implements some functions useful for handling multiple peripherals/centrals. This commit can also be tried by checking out the arduinoBLE 'multi_connection' branch here https://github.com/arduino-libraries/ArduinoBLE/tree/multi-connection . 
Some examples can be found here https://github.com/arduino-libraries/ArduinoBLE/issues/50

**Comment by sprasadkrish** [comment]
Hi Paolo Calao ,

                 Thank you , As per your suggestion , I will modify the
sketches.
