### ISSUE TITLE
Support for NINA-B31 Modules

### ISSUE THREAD

**Issue by felixerdy** [arduino-libraries/ArduinoBLE#321]
I'm trying to modify the library in a way, so that I can use it on another board ([senseBox MCU mini](https://sensebox.shop/product/sensebox-mcu-mini)) together with the [Bluetooth Bee](https://sensebox.shop/product/bluetooth-bee) which is running on a NINA-B312 module. 

While I'm able to communicate with AT commands
```c
void setup() {
    Serial3.begin(115200);
    delay(500);
    Serial3.print("AT+UFACTORY\r");
    Serial3.flush();
}
```

I can't get the library running. I'm setting the HardwareSerial in the `src/utility/HCIUartTransport.cpp` but the `HCI.reset()` function in `src/local/BLELocalDevice.cpp` is failing. 

There are some differences between NINA-B30 and B31 modules, but I don't know if they have an effect on this library. 
<img width="668" alt="Screenshot 2023-08-30 at 23 46 05" src="https://github.com/arduino-libraries/ArduinoBLE/assets/12086004/694c17d4-fb82-47be-a186-532d1204c6eb">
Source: [NINA-B3 Data Sheet](https://docs.arduino.cc/resources/datasheets/NINA-B3-series.pdf)

**Comment by facchinm** [comment]
Hi @felixerdy ,
the NINA B31 module comes pre-flashed with u-connect firmware, that's why you are able to communicate via AT commands. The HCIUartTransport class expects an HCI H4 port listening on the other side to correctly interpret the protocol instead. 
To be able to use this library you should write from scratch a transport (akin to HCIVirtualTransportAT) that implements the functionalities over AT.
Unfortunately we don't support any similar board (the closest one is UNO R4 WiFi but in that case we have full control over the firmware).
