### ISSUE TITLE
No #defines for Nano 33 BLE/Sense in BLELocalDevice.cpp

### ISSUE THREAD

**Issue by rmlearney-digicatapult** [arduino-libraries/ArduinoBLE#64]
Looking at the .begin() and .end() functions inside BLELocalDevice.cpp, there are defines for the following boards:

#if defined(ARDUINO_SAMD_MKRWIFI1010) || defined(ARDUINO_AVR_UNO_WIFI_REV2) || defined(ARDUINO_SAMD_NANO_33_IOT)

But there's nothing for the Nano 33 BLE or Sense.

Is this why you have to power cycle the board rather than issuing a BLE.end() followed by BLE.start() to reconnect? 

If I knew what the internal definition name was for the Nano 33 BLE, I'd try a quick fix myself, so if anyone can point me in the right direction, it would be much appreciated.

**Comment by facchinm** [comment]
Hi @rmlearney-digicatapult ,
all the boards mentioned need a special procedure to activate BLE since the module is off-chip. In Nano 33 BLE family the BLE functionality is inside the chip, so there's no need for that extra steps. Furthermore, it doesn't use an UART based transport but Cordio's one (https://github.com/arduino-libraries/ArduinoBLE/blob/master/src/utility/HCICordioTransport.cpp#L20)
